### ISSUE TITLE
Try.. except syntax

### ISSUE THREAD

**Issue by rasmusagren** [ginolhac/mapDamage#17]
Could you please change the syntax for error handling to work with the newer versions of Python?

This is in setup.py. 

From
`except (subprocess.CalledProcessError, OSError), error:
`

To
`except (subprocess.CalledProcessError, OSError) as error:
`

The newer syntax is used in Python >=2.6. Thanks!

Cheers,
Rasmus

**Comment by ginolhac** [comment]
Thanks Rasmus, would you mind doing a PR?

**Comment by rasmusagren** [comment]
I'm afraid I went back and used an old Python version instead :)

**Comment by ginolhac** [comment]
no worries ;)
