### ISSUE TITLE
Doesn't work on data from rescale_test/pe_test

### ISSUE THREAD

**Issue by NadiyaSitdykova** [ginolhac/mapDamage#18]
I tried to execute
 `mapDamage -i pe.sam -r ref.fasta`
and there is error message 
`The ACGT frequencies must be in the range 0 to 1`

I looked up this and it seems that the problem is that in the test data nucleotide frequency array looks like 0.5555556 0.2222222 0.2222222 0, 
i.e. frequency for T is zero, which is not what expected by mapdamage from line 4 in https://github.com/ginolhac/mapDamage/blob/master/mapdamage/Rscripts/stats/function.R#L4 Even though documentation doesn't say that zero frequencies are not allowed.

I changed reference file from "CGAGGGCGA" to "TGAAAACGA"  (so all frequencies > 0) and now it executes without this error

**Comment by ginolhac** [comment]
you are right, but do you only have such short references?

**Comment by NadiyaSitdykova** [comment]
Yes, I got this reference from here https://github.com/ginolhac/mapDamage/blob/master/mapdamage/rescale_test/pe_test/ref.fa

**Comment by NadiyaSitdykova** [comment]
I've tried pe.sam and reference CGAATACGA and then if failed with another error:
[https://gist.github.com/NadiyaSitdykova/eae941d240c2ffaed0bb75fc97fa6bc4](url)

So I dig into the code and found that in function calcSampleStats the quantile() called without na.rm=TRUE argument. I guess on real data also could be some missing values or NaNs so I treated this problem as a bug and created a patch [https://anonscm.debian.org/cgit/debian-med/mapdamage.git/tree/debian/patches/fix_quantile_na_rm.patch](url)

Please, let me know if you think that it's not a bug and that datasets which gives NaNs are not allowed.

**Comment by ginolhac** [comment]
I added new test and added `na.rm = TRUE` in the `quantile` calls. Should fix, sorry for the long delay
