### ISSUE TITLE
Missing zlib.h

### ISSUE THREAD

**Issue by jerry1333** [ginolhac/mapDamage#19]
It's not an issue but is may be annoying :)
Some people may be missing make / gcc / zlib.h 
```
$ sudo python setup.py install
running install
gcc -g -Wall -O2 -Wno-unused-function seqtk.c -o seqtk -lz -lm
seqtk.c:31:18: fatal error: zlib.h: No such file or directory
compilation terminated.
Makefile:5: recipe for target 'seqtk' failed
make: *** [seqtk] Error 1
Cannot compile seqtk
```
while trying to do:
```sudo python setup-py install```

It should be mentiones as note in install manual.

For my ubuntu i had to:
```sudo apt-get install make gcc libz-dev```

**Comment by ginolhac** [comment]
Thanks!
