### ISSUE TITLE
Please consider porting to Python3

### ISSUE THREAD

**Issue by tillea** [ginolhac/mapDamage#20]
Hi,
as you know I packaged mapDamage for Debian.  The upcoming release will be the latest featuring Python2.  It would be sensible to port mapDamage to Python3 in the not so distant future.
Kind regards, Andreas.

**Comment by ginolhac** [comment]
WIP in https://github.com/ginolhac/mapDamage/tree/python3

**Comment by tillea** [comment]
On Tue, Oct 01, 2019 at 05:33:33AM -0700, Aurélien Ginolhac wrote:
> WIP in https://github.com/ginolhac/mapDamage/tree/python3
Thanks a lot.  It would be great if you would tag a new release once the port is finished.

**Comment by ginolhac** [comment]
you're welcome, it seems to work fine. I specified `python3` in shebang, because python2 doesn't work anymore. Is this acceptable? I don't have experience on this

**Comment by tillea** [comment]
On Tue, Oct 01, 2019 at 06:14:55AM -0700, Aurélien Ginolhac wrote:
> you're welcome, it seems to work fine. I specified `python3` in shebang, because python2 doesn't work anymore. Is this acceptable? I don't have experience on this
Yes '#!/usr/bin/python3' is what is used in Debian and works here.

**Comment by ginolhac** [comment]
thanks! https://github.com/ginolhac/mapDamage/releases/tag/2.1.0 is there.

**Comment by tillea** [comment]
Very cool.  Thanks a lot.
I think there is one remaining [issue](https://salsa.debian.org/med-team/mapdamage/blob/master/debian/patches/fix_rescale_test.patch).  However, even if you apply that patch the test script throws:

    $ python3 rescale_test.py
    EE
    ======================================================================
    ERROR: test_longalignshortread (__main__.testCases)
    Check if fails on an aligment longer than the read
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "rescale_test.py", line 53, in test_longalignshortread
        rescale.rescale_qual(ref,options,debug=True)
      File "/usr/lib/python3/dist-packages/mapdamage/rescale.py", line 311, in rescale_qual
        rescale_length_5p=options.rescale_length_5p,
    AttributeError: 'Values' object has no attribute 'rescale_length_5p'

    ======================================================================
    ERROR: test_paired_end_file (__main__.testPairedFile)
    Test, paired end SAM file
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "rescale_test.py", line 43, in test_paired_end_file
        rescale.rescale_qual(ref,options,debug=True)
      File "/usr/lib/python3/dist-packages/mapdamage/rescale.py", line 311, in rescale_qual
        rescale_length_5p=options.rescale_length_5p,
    AttributeError: 'Values' object has no attribute 'rescale_length_5p'

    ----------------------------------------------------------------------
    Ran 2 tests in 0.001s

    FAILED (errors=2)

I realised that this is not new and also happended at the previous version of mapdamage.
Kind regards, Andreas.

**Comment by ginolhac** [comment]
Thanks for reporting! I will have a look. I don't think we expect paired end bams. But it should at least be handled gracefully

**Comment by ginolhac** [comment]
with the last commit, paired-end BAMs give an error and a new test (fake single-end) is included.
The output should look like this:

```
mapdamage (python3)> python3 mp_test.py
Started with the command: /usr/local/bin/mapDamage -i tests/test.bam -r tests/fake1.fasta -d tests/results --no-stats
	Reading from 'tests/test.bam'
	Writing results to 'tests/results/'
pdf tests/results/Fragmisincorporation_plot.pdf generated
additional tests/results/Length_plot.pdf generated
Successful run
.
----------------------------------------------------------------------
Ran 1 test in 2.889s

OK
```

there is also a rescaled BAM I could add but the test run take some time, I don't know how this is tolerable. For now, we can just use this test that test if the `--no-stats` part works well.
Best wishes

**Comment by ginolhac** [comment]
Of note, I added a rescale test as @hakon-jon  did for the PE data but now for the SE example BAM.

**Comment by ginolhac** [comment]
see new [v2.2.0](https://github.com/ginolhac/mapDamage/tree/2.2.0) where python3 as master branch, please reopen if needed.
