### ISSUE TITLE
File and column name discrepancy in mutation tables

### ISSUE THREAD

**Issue by mmaitenat** [ginolhac/mapDamage#21]
Hi there,
I just run mapDamage on some data. One of the generated files is named 3pGtoA_freq.txt. However, when I look inside the file, the column name is 5pG>A. Could you please clarify which end (3p or 5p) correspond those frequencies to? 

Many thanks,

Maitena.

**Comment by ginolhac** [comment]
filenames were correct, thanks for reporting
