### ISSUE TITLE
Error performing Bayesian estimates

### ISSUE THREAD

**Issue by grendon** [ginolhac/mapDamage#23]
This is the snippet that gets printed to to screen when it fails:

`Error in cxxfunction(signature(I_la = "numeric", I_la_disp = "numeric",  :
  could not find function "signature"
Calls: source ... source -> withVisible -> eval -> eval -> cxxfunction
10: (function (e)
    {
        traceback(2)
        quit(status = 1)
    })()
9: cxxfunction(signature(I_la = "numeric", I_la_disp = "numeric",
       I_nu = "numeric", I_m = "numeric", I_lengths = "numeric",
       I_mLe = "numeric", I_fo = "numeric", I_iter = "numeric",
       I_ds_protocol = "numeric"), includes = "\n                  #include <gsl/gsl_randist.h>\n                  int genOverHang(double la,double la_disp)\n                  {\n                      double r = ((double) rand() / (RAND_MAX));\n                      int i = -1;\n                      double p = 0;\n                      double term = -500; \n                      while (p<r){\n                          if (i==-1){\n                              term = 1;\n                          }else {\n                              term = 0;\n                          }\n                          p = p + (gsl_ran_negative_binomial_pdf(i+1,la,la_disp)+term)/2;\n                          i++;\n                      }\n                      return(i);\n                  }\n                  ",
       body = "\n              srand(time(0)); \n        Rcpp::NumericVector la(I_la);\n        Rcpp::NumericVector la_disp(I_la_disp);\n        Rcpp::NumericVector nu(I_nu);\n        Rcpp::NumericVector m(I_m);\n        Rcpp::NumericVector les(I_lengths);\n        Rcpp::NumericVector mLe(I_mLe);\n        Rcpp::NumericVector fo(I_fo);\n        Rcpp::NumericVector iter(I_iter);\n        Rcpp::NumericVector ds_protocol(I_ds_protocol);\n//\n        Rcpp::NumericVector output(mLe[0]);\n        Rcpp::NumericVector reduced_output(m[0]);\n        if (ds_protocol[0]==0){\n            for (int j = 0; j < m[0];j++){\n                reduced_output(j) = 1;\n            }\n            return(reduced_output);\n        }else {\n            for (int i = 0; i < iter[0];i++ ){\n//\n                double left_o_hang = genOverHang(la[0],la_disp[0]);\n                double right_o_hang = genOverHang(la[0],la_disp[0]);\n                double o_hang  = left_o_hang+right_o_hang;\n//              \n                if (o_hang>=les(i)){\n                    //Single stranded sequence\n                    for (int j = 0; j <les(i);j++){\n                        output(j) = output(j)+1;\n                    }\n                } else {\n                    Rcpp::NumericVector r = runif(1);\n                    if (r[0]< (1-nu[0])/((les[i]-o_hang-1)*nu[0]+(1-nu[0]))){\n                        for (int j = 0; j <(les[i]-right_o_hang);j++){\n                            output(j) = output(j)+1;\n                        }\n                        //The right overhang is always G>A for the double stranded but \n                        //Here we will make the assumption that the pattern is symmetric \n                        //for practical reasons We can't  do that ....\n                    }else {\n                        Rcpp::NumericVector sa = floor(runif(1,0,les[i]-o_hang))+left_o_hang;\n                        for (int j = 0; j <=sa[0];j++){\n                            output(j) = output(j)+1;\n                        }\n                    }\n                }\n            }\n            if (fo(0)){\n                //Only considering the forward part\n                for (int j = 0; j < m[0];j++){\n                    reduced_output(j) = output(j)/iter(0);\n                }\n            }else {\n                for (int j = 0; j < m[0]/2;j++){\n                    reduced_output(j) = output(j)/iter(0);\n                    reduced_output(m[0]-j-1) = 1-output(j)/iter(0);\n                }\n            }\n            return(reduced_output);\n        }\n",
       plugin = "RcppGSL")
8: eval(expr, envir, enclos)
7: eval(ei, envir)
6: withVisible(eval(ei, envir))
5: source(paste(path_to_mapDamage_stats, "function.R", sep = ""))
4: eval(expr, envir, enclos)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source(paste(path_to_mapDamage_stats, "main.R", sep = ""))
The Bayesian statistics program failed to finish
Traceback (most recent call last):
  File "/home/apps/software/mapDamage/2.0.5-IGB-gcc-4.9.4-Python-2.7.13/bin/mapDamage", line 382, in <module>
    sys.exit(main())
  File "/home/apps/software/mapDamage/2.0.5-IGB-gcc-4.9.4-Python-2.7.13/bin/mapDamage", line 365, in main
    mapdamage.rscript.run_stats(options)
  File "/home/apps/software/mapDamage/2.0.5-IGB-gcc-4.9.4-Python-2.7.13/lib/python2.7/site-packages/mapdamage/rscript.py", line 144, in run_stats
    raise e
subprocess.CalledProcessError: Command '['Rscript', '/home/apps/software/mapDamage/2.0.5-IGB-gcc-4.9.4-Python-2.7.13/lib/python2.7/site-packages/mapdamage/Rscripts/stats/runGeneral.R', '--args', '30', '10000', '10', '50000', '0', '0', '1', '1', '0', '0', '1', '12', 'Sunol_stickle_CAATGCGA-GACGAACT_L008_R1_001.ready_mapDamage_len80_Q20/', '/home/apps/software/mapDamage/2.0.5-IGB-gcc-4.9.4-Python-2.7.13/lib/python2.7/site-packages/mapdamage/Rscripts/stats/', 'Sunol_stickle_CAATGCGA-GACGAACT_L008_R1_001.ready_mapDamage_len80_Q20/Stats_out', '0', '0', '0', 'Sunol_stickle_CAATGCGA-GACGAACT_L008_R1_001.ready_mapDamage_len80_Q20/acgt_ratio.csv', '0', '0']' returned non-zero exit status 1

Error in cxxfunction(signature(I_la = "numeric", I_la_disp = "numeric",  : could not find function "signature"

`

Your help will be appreciated.

**Comment by ginolhac** [comment]
Hey, did you try the latest version? Mikkel solved this issue a year ago in commit https://github.com/ginolhac/mapDamage/commit/9abe4051a2449194afc354e05df6531cf894449d
