### ISSUE TITLE
can not find pysam

### ISSUE THREAD

**Issue by BiodivGenomic** [ginolhac/mapDamage#24]
Hello,
I would like to use mapDamage, thus I installed it, everything looked fine, but when I try to run it, I get this error :
Error: Could not import required module 'pysam':
	- No module named pysam
       If module is not installed, please download from 'http://code.google.com/p/pysam/'.
       A local install may be performed using the following command:
       $ python setup.py install --user
I installed pysam using both conda and pip, each time it said it was properly installed, but always the same error appeared when running it.
I'm using Ubuntu 18.04.
Any help would be useful, thanks in advance !

**Comment by BiodivGenomic** [comment]
Hello,
I get an other error :
```
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: No module named libchtslib
>>> 

```

**Comment by ginolhac** [comment]
then it is not an issue with mapDamage but with your install of `pysam`. Its dependencies are not installed properly

**Comment by BiodivGenomic** [comment]
Thank you for your reply.  I fixed that error, but still get the same error as in the first message...

**Comment by ginolhac** [comment]
as you can see [here](https://github.com/ginolhac/mapDamage/blob/d251da09dbdf0776cdf6f439fe9347b473154d2e/bin/mapDamage#L47) mapDamage is only testing `import pysam`. Maybe you are running different versions of python, otherwise, I cannot help more than this

**Comment by BiodivGenomic** [comment]
Thank you for your help... I installed it on macosX 10.12, and I can run it (but see other issues in other thread).
