### ISSUE TITLE
Warnings on macosX 10.12 and gfortran issue (already solved)

### ISSUE THREAD

**Issue by BiodivGenomic** [ginolhac/mapDamage#26]
Hello,
the first part of mapDamage ran fine, but I got this error when performing Bayesian estimates :
`
....
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [file3962273b7820.so] Error 1

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: 
  2: // includes from the plugin
  3: #include <RcppGSL.h>
  4: #include <Rcpp.h>
  5: 
  6: 
  7: #ifndef BEGIN_RCPP
  ....
`

I solved it installing gcc from binaries, but then I get 

`Performing Bayesian estimates
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
file4d6011c557fb.cpp:46:5: warning: unused variable 'm' [-Wunused-variable]
int m = Vm[0];
    ^
1 warning generated.
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
Starting grid search, starting from random values
Adjusting the proposal variance iteration  1  
Adjusting the proposal variance iteration  2  
Adjusting the proposal variance iteration  3  
Adjusting the proposal variance iteration  4  
Adjusting the proposal variance iteration  5  
Adjusting the proposal variance iteration  6  
Adjusting the proposal variance iteration  7  
Adjusting the proposal variance iteration  8  
Adjusting the proposal variance iteration  9  
Adjusting the proposal variance iteration  10  
Done burning, starting the iterations
Done with the iterations, finishing up
Writing and plotting to files
Warning: Ignoring unknown aesthetics: aes_string
Warning: Ignoring unknown aesthetics: y
Warning: Ignoring unknown aesthetics: y
Warning: Ignoring unknown aesthetics: y
Warning messages:
1: In model.matrix.default(mt, mf, contrasts) :
  non-list contrasts argument ignored
2: In model.matrix.default(mt, mf, contrasts) :
  non-list contrasts argument ignored
Successful run
`

I'm wondering if the warnings can impact the results ?
Thanks in advance !

**Comment by ginolhac** [comment]
warnings could be ignored, yes `aes_string` should be replaced by some modern tidyeval statements now. Closing for now
