### ISSUE TITLE
single-end alignment required?

### ISSUE THREAD

**Issue by ginolhac** [ginolhac/mapDamage#27]
From @pratas (and issue #25) :
> Last time I used mapDamage was on single end data. Now I got:
> 
> Started with the command: /home/pratas/miniconda3/bin/mapDamage -d ../output_data/TRACES_mtdna_damage -i FIL-mt_aligned_sorted.bam -r mtDNA.fa
> alignment file must be single-ended
> alignment file must be single-ended
> 
> It seems that the issue is paired-end data...
> I removed the --rescale option and it is with the same issue.
> I'm using bowtie2:
> 
> (FASTQ files: o_fw_pr.fq, o_rv_pr.fq, o_fw_unpr.fq, o_rv_unpr.fq)
> 
> bowtie2 -a --threads 40 -x index_file -1 o_fw_pr.fq -2 o_rv_pr.fq -U o_fw_unpr.fq,o_rv_unpr.fq > aligned.sam
> samtools sort aligned.sam > mt_aligned_sorted.bam
> samtools index mt_aligned_sorted.bam mt_aligned_sorted.bam.bai
> samtools view -bh -F4 mt_aligned_sorted.bam > FIL-mt_aligned_sorted.bam;
> mapDamage --rescale -d ../output_data/TRACES_mtdna_damage -i FIL-mt_aligned_sorted.bam -r mtDNA.fa;
> 
> Any tip? (I'm sorry to write this here but I'm not sure where to write it)
> 
> Best regards,
> D

**Comment by ginolhac** [comment]
yes, from now I restricted `mapDamage` to work with single-end data.
Why?

- for ancient DNA, you expect short templates because of fragmentation
- most paired-end reads should overlap. You can use [AdapterRemoval2](https://github.com/MikkelSchubert/adapterremoval) with the option `--collapse` to produce merged reads from paired-end data
- the length estimation plots/tables never really worked out with paired-end BAMs
- nor the rescaling.

For now, I think this new restriction to single-end BAMs will stay. And I recommend merging your reads into one single-end template.

**Comment by pratas** [comment]
I've used AdapterRemoval2 according to:

AdapterRemoval --threads 40 --file1 FW_READS.fq.gz --file2 RV_READS.fq.gz --outputcollapsed reads.fq --trimns --trimqualities --minlength 30 --collapse --adapter-list adapters_ar.fa
bwa index mtDNA.fa
bwa mem -t 8 -I 0 -O 2 -N 0.02 -L 1024 -E 7 mtDNA.fa reads.fq > x.sam
samtools view -bSh x.sam > x.bam
samtools view -bh -F4 x.bam > mt_aligned_sorted.bam
samtools view -bh -F4 mt_aligned_sorted.bam > FIL-mt_aligned_sorted.bam;
mapDamage --rescale -d ../output_data/TRACES_mtdna_damage -i FIL-mt_aligned_sorted.bam -r mtDNA.fa;

and got the following:

Started with the command: /home/pratas/miniconda3/bin/mapDamage --rescale -d ../output_data/TRACES_mtdna_damage_A -i FIL-mt_aligned_sorted-A.bam -r mtDNA.fa
	Reading from 'FIL-mt_aligned_sorted-A.bam'
	Writing results to '../output_data/TRACES_mtdna_damage_A/'
pdf ../output_data/TRACES_mtdna_damage_A/Fragmisincorporation_plot.pdf generated
additional ../output_data/TRACES_mtdna_damage_A/Length_plot.pdf generated
Performing Bayesian estimates
/home/pratas/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -llapack
/home/pratas/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/home/pratas/miniconda3/lib/R/share/make/shlib.mk:6: file7bf761474eb.so] Error 1

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: 
  2: // includes from the plugin
  3: #include <RcppGSL.h>
... (The rest of the code)

What is happening? Missing some binaries?

D

**Comment by pratas** [comment]
From the code, please ignore the double version of "samtools view -bh -F4"

**Comment by ginolhac** [comment]
I have no idea. I am testing with this docker container 
```bash
docker run -ti bioconda/bioconda-utils-build-env /bin/bash
```
and seems to run fine, this container only have `conda` utilities.

```bash
conda install -c bioconda mapdamage2=2.1.1=pyr36_1
```

then, I am testing the new fake file I pushed to python3 branch:
```bash
(base) [root@130e33e3c004 tests]# mapDamage -i test.bam -r fake1.fasta --rescale
Started with the command: /opt/conda/bin/mapDamage -i test.bam -r fake1.fasta --rescale
	Reading from 'test.bam'
	Writing results to 'results_test/'
pdf results_test/Fragmisincorporation_plot.pdf generated
additional results_test/Length_plot.pdf generated
Performing Bayesian estimates
Warning, To few substitutions to assess the nick frequency, using constant nick frequency instead
Starting grid search, starting from random values
Adjusting the proposal variance iteration  1  
Adjusting the proposal variance iteration  2  
Adjusting the proposal variance iteration  3  
Adjusting the proposal variance iteration  4  
Adjusting the proposal variance iteration  5  
Adjusting the proposal variance iteration  6  
Adjusting the proposal variance iteration  7  
Adjusting the proposal variance iteration  8  
Adjusting the proposal variance iteration  9  
Adjusting the proposal variance iteration  10  
Done burning, starting the iterations
Done with the iterations, finishing up
Writing and plotting to files
Warning messages:
1: Removed 8 rows containing missing values (geom_point). 
2: Removed 7 rows containing missing values (geom_point). 
3: Removed 22 rows containing missing values (geom_point). 
4: Removed 8 rows containing missing values (geom_errorbar). 
5: Removed 7 rows containing missing values (geom_errorbar). 
6: Removed 22 rows containing missing values (geom_errorbar). 
7: Removed 1 rows containing missing values (geom_path). 
8: Removed 15 rows containing missing values (geom_path). 
Rescaling BAM: 'test.bam' -> 'results_test/test.rescaled.bam'
	The expected substition frequencies before and after scaling using the scaled qualities as probalities:
	CT	0.06226411977920493		0.04154582001463545
	TC	0.020395286584806528		0.020395286584806528
	GA	0.04400459948304954		0.037925529563819345
	AG	0.05355350777642983		0.05355350777642983
	Quality metrics before and after scaling
	CT-Q0 	5		5
	CT-Q10 	5		2
	CT-Q20 	3		2
	CT-Q30 	3		2
	CT-Q40 	0		0
	GA-Q0 	5		5
	GA-Q10 	5		4
	GA-Q20 	1		0
	GA-Q30 	1		0
	GA-Q40 	0		0
Successful run
```

According to [this comment on SO](https://stackoverflow.com/questions/47664289/cannot-find-llibrary-r#comment82288327_47664289) by Dirk who knows very well all this, I might use `conda` installation only for python and not R if it is too much hassle. 
Then the alternative is to properly install R via CRAN and the 4 packages in a the regular way. R is such language anyway, I doubt you won't need it on your computer at some point.

**Comment by pratas** [comment]
Please, can you send me the test.bam and fake1.fasta files, so I'm able to discard any error happening before mapDamage usage? (pratas@ua.pt)

**Comment by ginolhac** [comment]
there are now included in the package:

- https://raw.githubusercontent.com/ginolhac/mapDamage/python3/mapdamage/tests/fake1.fasta
- https://raw.githubusercontent.com/ginolhac/mapDamage/python3/mapdamage/tests/test.bam

**Comment by pratas** [comment]
mapDamage -r fake1.fasta -i test.bam 
Started with the command: /home/pratas/miniconda3/bin/mapDamage -r fake1.fasta -i test.bam
	Reading from 'test.bam'
	Writing results to 'results_test/'
pdf results_test/Fragmisincorporation_plot.pdf generated
additional results_test/Length_plot.pdf generated
Performing Bayesian estimates
/home/pratas/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -llapack
/home/pratas/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/home/pratas/miniconda3/lib/R/share/make/shlib.mk:6: file209c193c1b3b.so] Error 1

ERROR(s) during compilation: source code errors or compiler configuration errors!


Yes, it really seems that it is the R...
Thanks!

D

**Comment by ginolhac** [comment]
yes, you R install or more precisely the toolchain supplied by conda is not complete.
closing for now and I will wait to see how this bioconda recipe works for others. If it doesn't I will revert it to have separated R / python environments. Best regards

**Comment by pratas** [comment]
Than you Aurélien! Best regards

**Comment by JeremyLGauthier** [comment]
I'm quite disturbed with the new single end mapping restrictions...

You're absolutely right that for ancient DNA you expect short templates because of fragmentation and most paired-end reads should overlap and can be collapsed with AdapterRemoval2.

The problem is the "most", because this is not always the case, especially when you work on ancient DNA well preserved as in my case... this means all non-overlapping pairs are lost ?

There is no way to keep the two options in Mapdamage ? single-end and paired-end ?
Than you a lot.

**Comment by ginolhac** [comment]
at least with collapsed overlapping reads, you are sure about the full fragment sequence. To assess authenticity this is sufficient. For down-scaling qualities this is another story, but as the development of mapDamage is in frozen state, I doubt an option for paired-end reads will be provided

**Comment by JeremyLGauthier** [comment]
The problem is that I use Mapdamage to correct deamination patterns and then generate reliable consensuses. I just checked my data and when I keep only the collapsed reads I lose a third of my data... I think I'll continue to use a version of Mapdamage before this release.
