### ISSUE TITLE
Installing mapDamage in a virtual environment.....

### ISSUE THREAD

**Issue by ZhexueM** [ginolhac/mapDamage#28]
Hello together,

I want to install your PYTHON - Module in an virtual Environment on our cluster, but I can't find any informations for this way.

So, please can you help me?
Best regards from Germany

Matthias

**Comment by ginolhac** [comment]
Hello Matthias,

I guess it will be with `-n my_env` is what you are after https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

closing as not related to mapDamage

**Comment by ZhexueM** [comment]
Hello together,

 

thank you very much for your help.

BUT this can´t solved my problem, because I don´t use CONDA for Virtual Environment. I´m using PYTHON3 as Environment….

 

Best regards and take care….

 

 

 

Matthias Krawutschke, Dipl. Inf.

 

Universität Potsdam
ZIM - Zentrum für Informationstechnologie und Medienmanagement

Team Infrastruktur Server und Storage 
Spezialized: High-Performance-Computing and Kubernetes

 

 

Campus Am Neuen Palais: Am Neuen Palais 10 | 14469 Potsdam
Tel: +49 331 977-153065, Fax: +49 331 977-1750

 

Internet:  <https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html> https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html

 

 

Von: Aurélien Ginolhac <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 14:31
An: ginolhac/mapDamage <mapDamage@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [ginolhac/mapDamage] Installing mapDamage in a virtual environment..... (#28)

 

Hello Matthias,

I guess it will be with -n my_env is what you are after https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

closing as not related to mapDamage

**Comment by MikkelSchubert** [comment]
This is not really a mapDamage issue, but you can install mapDamage in a virtual environment using the 'venv' module:

	https://docs.python.org/3/library/venv.html

The following shows the commands that you might use:

 	wget https://github.com/ginolhac/mapDamage/archive/2.2.0.tar.gz
 	tar xvzf 2.2.0.tar.gz
 	cd mapDamage-2.2.0/
 	python3 -m venv venv
 	./venv/bin/python3 -m pip install cython
 	./venv/bin/python3 -m pip install pysam
 	./venv/bin/python3 setup.py install

After that, you can run mapDamage as follows:

 	./venv/bin/mapDamage

**Comment by ZhexueM** [comment]
Dear Mikkel,

 

i had do that in this way, as your write me.

But I´ve got the error – Messages, that I wrote here ☹ And I don´t know why.

 

Best regards….

 

 

 

Matthias Krawutschke, Dipl. Inf.

 

Universität Potsdam
ZIM - Zentrum für Informationstechnologie und Medienmanagement

Team Infrastruktur Server und Storage 
Spezialized: High-Performance-Computing and Kubernetes

 

 

Campus Am Neuen Palais: Am Neuen Palais 10 | 14469 Potsdam
Tel: +49 331 977-153065, Fax: +49 331 977-1750

 

Internet:  <https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html> https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html

 

 

Von: Mikkel Schubert <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 15:23
An: ginolhac/mapDamage <mapDamage@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [ginolhac/mapDamage] Installing mapDamage in a virtual environment..... (#28)

 

This is not really a mapDamage issue, but you can install mapDamage in a virtual environment using the 'venv' module:

https://docs.python.org/3/library/venv.html

The following shows the commands that you might use:

wget https://github.com/ginolhac/mapDamage/archive/2.2.0.tar.gz
tar xvzf 2.2.0.tar.gz
cd mapDamage-2.2.0/
python3 -m venv venv
./venv/bin/python3 -m pip install cython
./venv/bin/python3 -m pip install pysam
./venv/bin/python3 setup.py install

After that, you can run mapDamage as follows:

./venv/bin/mapDamage

**Comment by MikkelSchubert** [comment]
You did include any error messages.

If you need further help installing software on your cluster, then please contact whoever is running that cluster and ask them for help. They should be able to assist you better than we can.

**Comment by ZhexueM** [comment]
Dear Mikkel,

 

that is wrong, because on my first eMail on this list I sent my Error – Message.

And sorry, I´m the player of our HPC – Service; I manage it.

My problem is:

 

Hello together,

 

i want to install your software for our department Biology & BioChemie, but i´ve got some error, if I ran “mapDamage” from Commandline.

The result is:

 

Traceback (most recent call last):

  File "/hpc-cloud/uprojects/packages/.virtual/python3.8.1/mapDamage/2.2.0/bin/mapDamage", line 5, in <module>

    from mapdamage.main import entry_point

  File "/hpc-cloud/uprojects/packages/.virtual/python3.8.1/mapDamage/2.2.0/lib/python3.8/site-packages/mapdamage/__init__.py", line 7, in <module>

    import mapdamage.composition

  File "/hpc-cloud/uprojects/packages/.virtual/python3.8.1/mapDamage/2.2.0/lib/python3.8/site-packages/mapdamage/composition.py", line 4, in <module>

    import mapdamage.seqtk as seqtk

ImportError: /hpc-cloud/uprojects/packages/.virtual/python3.8.1/mapDamage/2.2.0/lib/python3.8/site-packages/mapdamage/seqtk.cpython-38-x86_64-linux-gnu.so: undefined symbol: gzclose

 

But I can´t find some errors, etc. – so please can you help me?

 

Best regards….

 

 

 

Matthias 

 

Von: Mikkel Schubert <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 15:39
An: ginolhac/mapDamage <mapDamage@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [ginolhac/mapDamage] Installing mapDamage in a virtual environment..... (#28)

 

You did not include any error messages.

If you need further help installing software on your cluster, then please contact whoever is running that cluster and ask them for help. They should be able to assist you better than we can.

**Comment by MikkelSchubert** [comment]
I don't know where you sent that error message, but it did not end up in my hands (or on github).

You also appear to be running a direct checkout of the master branch instead of a tagged release.
That is not recommended, as such a checkout cannot be trusted to be ready for general use, as you've just discovered.  I've pushed a commit that may fix the problem you are experiencing, but you should not be using the development version of mapDamage in the first place.

Please download and install a tagged release, or install mapDamage using conda or via your distro's package manager (if available).

**Comment by ginolhac** [comment]
A user (Weisz, David) found the fix for this issue in the `setup.py` to specify the `zlib` we have to 
```
ext_modules=[Extension("mapdamage.seqtk", ["mapdamage/seqtk/seqtk.c"], libraries = ['z'])],
```

I will fix this and make a new release so also the work from Mikkel with SE reads is out

**Comment by ZhexueM** [comment]
Dear Mikkel,

 

thank your very much for your help.

But I can´t find an other release then I found it on this site:

 

https://github.com/ginolhac/mapDamage

 

Is it okay, that I can download now this release from this site?

 

Best regards….

 

 

 

Matthias Krawutschke, Dipl. Inf.

 

Universität Potsdam
ZIM - Zentrum für Informationstechnologie und Medienmanagement

Team Infrastruktur Server und Storage 
Spezialized: High-Performance-Computing and Kubernetes

 

 

Campus Am Neuen Palais: Am Neuen Palais 10 | 14469 Potsdam
Tel: +49 331 977-153065, Fax: +49 331 977-1750

 

Internet:  <https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html> https://www.uni-potsdam.de/de/zim/angebote-loesungen/hpc.html

 

 

Von: Mikkel Schubert <notifications@github.com> 
Gesendet: Sonntag, 10. Mai 2020 17:27
An: ginolhac/mapDamage <mapDamage@noreply.github.com>
Cc: ZhexueM <krawutschke@uni-potsdam.de>; Author <author@noreply.github.com>
Betreff: Re: [ginolhac/mapDamage] Installing mapDamage in a virtual environment..... (#28)

 

I don't know where you sent that error message, but it did not end up in my hands (or on github).

You also appear to be running a direct checkout of the master branch instead of a tagged release.
That is not recommended, as such a checkout cannot be trusted to be ready for general use, as you've just discovered. I've pushed a commit that may fix the problem you are experiencing, but you should not be using the development version of mapDamage in the first place.

Please download and install a tagged release, or install mapDamage using conda or via your distro's package manager (if available).
