### ISSUE TITLE
Plot_composition

### ISSUE THREAD

**Issue by valery-shap** [ginolhac/mapDamage#33]
Hello,

I have single-end ancient reads of human. I've tried different commands of mapDamage but the result is the same. Instead of plot with clear points and line I have smth like that:

I don't know how to interpret this data and I'm trying to find a mistake.
The commads were:
mapDamage -d /home/ -i sorted.bam  -r GRCh38.primary_assembly.genome.fa
mapDamage -n 0.5 -d /home/ -i sorted.bam  -r GRCh38.primary_assembly.genome.fa
mapDamage --forward  -d /home/ -i sorted.bam  -r GRCh38.primary_assembly.genome.fa

I've tried to use only mapped bam too(-F 4)
![map_damage](https://user-images.githubusercontent.com/47143104/95073645-df7ab280-0715-11eb-96aa-0a63d55dcf63.png)
 The way i've got the bam file:
bwa index -p hg38 -a bwtsw GRCh38.primary_assembly.genome.fa
bwa aln hg38 my.fastq > my.sai
bwa samse hg38 my.sai my.fastq > my.sam
samtools view -b -o my.bam my.sam
samtools sort -o my_sorted.bam my.bam
samtools index my_sorted.bam

A lot of thanks,
Valery
Udp. when there is a bam file with mapping only X chromosome for example it's shown one big point for the position. M chr gives one big point and 2 small (up and down). So could you , please, write what does the point mean on this plot. Every point for every chromosome in the reference?

**Comment by ginolhac** [comment]
you are right, little dots `.` are the values for every chromosome. Big dots are the mean. For the X chr the mean is on the value so you don't see the `.`. For the chr M variance is huge and you have both values are seen up/down while the mean is in the middle.
Your data is a bit dispersed but the increase at position -1 is there, looks good to me

**Comment by valery-shap** [comment]
Sorry for disturbing you, I've been used the tool for the first time and worry about a lot of things)
so for example:
chrX
plot for A
i have 4 rows in the table for the first position: 3p+, 3p-, 5p+, 5p-
firstly from 3p+
choose A column 1351
choose mutation type with A, yes?(and how about deletion insertions and soft -clipping?)
G>A(18) , C>A, T>A, ->A   right?
count frequency for every type like in manual 18/1351 etc
count mean for all types
count this mean for every row(3p+, 3p-, 5p+, 5p) 
and this value will be the mean with big dot?
if the difference between 4 rows(like in M chromosome ) will be big, it is shown one big dot(mean) and small dots for every row? but i see 1 big dot and two small dots for the first position for M chromosome. so it looks like error visualization.
could i make the plot only with mean value?

A lot of thanks,
Valery

**Comment by valery-shap** [comment]
Sorry for disturbing you, I've been used the tool for the first time and worry about a lot of things)
so for example:
chrX
plot for A
i have 4 rows in the table for the first position: 3p+, 3p-, 5p+, 5p-
firstly from 3p+
choose A column 1351
choose mutation type with A, yes?(and how about deletion insertions and soft -clipping?)
G>A(18) , C>A, T>A, ->A   right?
count frequency for every type like in manual 18/1351 etc
count mean for all types
count this mean for every row(3p+, 3p-, 5p+, 5p) 
and this value will be the mean with big dot?
if the difference between 4 rows(like in M chromosome ) will be big, it is shown one big dot(mean) and small dots for every row? but i see 1 big dot and two small dots for the first position for M chromosome. so it looks like error visualization.
could i make the plot only with mean value?

A lot of thanks,
Valery

**Comment by ginolhac** [comment]
there is quite some confusion, the plot is the bases composition, the misincorporation is something else.
could you please clarify the question and have a detailed example?

**Comment by valery-shap** [comment]
Sorry for my mistake. Seems that I find the answer in the suppelementary of the article(mapDamage:testing for damage patterns in ancient DNA).
There is the picture:
![base_comp](https://user-images.githubusercontent.com/47143104/95686703-44e40d00-0c08-11eb-9af5-ea0a97d09a44.png)


Am i right if
the reference and the read (that aligned) are merged in one sequence and then just count for all these merged sequences:
for example the frequence of A base to be on the first position of the read. if A  =20 and total 365 so it'll be 20/365. 
and this frequence is counted for every chromosome. And the big point on the plot is the mean of the data by all chromosomes.
What is reason to count this frequency separately for every chromosome and plot it? Counld I plot only one mean value for all chromosomes?

A lot of thanks,
Valery

**Comment by valery-shap** [comment]
Sorry,one more question
if i have only single-end reads, i shouldn't see A/G change in the 3' end on the bottom plot and on the top plot there shouldn't be a peak in the right part of the plots. Right?
Like it is on these plots.
![base_comp2](https://user-images.githubusercontent.com/47143104/95727319-aa74df80-0c82-11eb-8163-33ef670288fc.png)

Best regards,
Valery

**Comment by ginolhac** [comment]
if you have long enough reads vs sequencing length yes.

For plotting only the means, you could use aggregation at the chromosome level too

```r
library(tidyverse)

dnacomp <- read_tsv("results_NSim2F_m/dnacomp.txt", comment = "#")
dnacomp %>%
  # only for main chromosomes
  filter(str_detect(Chr, "^chr")) %>%
# long format for summarisation
  pivot_longer(cols = c(A:T),
               names_to = "base",
               values_to = "count") %>% 
  # group also by Chr to get all chr values
  # group_by(Chr, End, Pos, base) %>% 
  group_by(End, Pos, base) %>% 
  summarise(across(c(Total, count), sum)) %>% 
  ungroup() %>% 
  mutate(freq = count / Total) -> dnasum
```
then plot 

```r
dnasum %>% 
  mutate(End = fct_relevel(End, "5p")) %>% 
  ggplot(aes(x = Pos, y = freq, colour = base)) +
  geom_point() +
  facet_grid(End ~ base) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  coord_cartesian(ylim = c(0, 0.5), xlim = c(-10, 10))
```

![image](https://user-images.githubusercontent.com/710181/95727901-1c492b00-0c7b-11eb-9da4-e11f36671005.png)

joining the `dnacomp.txt` as zip file for reproducibility
[dnacomp.zip](https://github.com/ginolhac/mapDamage/files/5364095/dnacomp.zip)

**Comment by valery-shap** [comment]
All reads are 50 bp long. 
Thank you very much. It works.

Best regards,
Valery

**Comment by ginolhac** [comment]
great

**Comment by valery-shap** [comment]
Hello again)

Today i've tried bam pipeline from Paleomix with the same reads and the reference and the result was different! With one mean big point and on the top plot there are peaks in the right side.
![base_comp3](https://user-images.githubusercontent.com/47143104/95778278-70cac580-0cd0-11eb-99d9-94ff24252d33.png)
Unfortunately, i can't explain why it is so. Could it be because of some preprocessing of the reads and bam file? I think no)
And i can't explain why there is no peak on the bottom plot(A/G), but there are peaks on the top plots on the right side(3' of the read)

Best regards,
Valery
