### ISSUE TITLE
Error in quantile.default(newX[, i], ...) :   missing values and NaN's not allowed if 'na.rm' is FALSE

### ISSUE THREAD

**Issue by astulaaa** [ginolhac/mapDamage#35]
Hello,

I ran mapDamage on a very low coverage samples and found such error in a log file :Error in quantile.default(newX[, i], ...) :
missing values and NaN's not allowed if 'na.rm' is FALSE:" I will attach the whole log file. 
How badly does this error affect the output and accuracy of estimates? Can I just ignore it or is there a way to work around it?

Thank you,
Asta
[mapDamage.e.txt](https://github.com/ginolhac/mapDamage/files/6113249/mapDamage.e.txt)
[mapDamage.o.txt](https://github.com/ginolhac/mapDamage/files/6113250/mapDamage.o.txt)

**Comment by ginolhac** [comment]
Hello,

I see `Warning, To few substitutions to assess the nick frequency, using constant nick frequency instead` for you have very low coverage, low damages so running the Bayesian seems a bit risky. You can still disable this inference with `--no-stats` and see the plots to see how it looks like.
