### ISSUE TITLE
Error: Could not import required module 'pysam' when conda provides pysam<0.15

### ISSUE THREAD

**Issue by zjnolen** [ginolhac/mapDamage#39]
When installing with conda, if a pysam version <0.15 is installed as a dependency I get this error on Linux:

```
>conda install mapdamage2

>mapDamage
Error: Could not import required module 'pysam':
	- libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
       If module is not installed, please download from 'http://code.google.com/p/pysam/'.
       A local install may be performed using the following command:
       $ python setup.py install --user
```

This happens both on installs on the cluster I'm using as well as my local laptop. I've tried manually specifying versions 0.15, 0.16, and 0.17 when installing (`conda install mapdamage2 pysam=0.##`) and no longer get the error nor any package conflicts.

It seems this is the conda solver for some reason not grabbing the latest compatible version. It happens mainly when using mamba as the solver replacement, which is how the mapDamage Snakemake wrapper deploys the software and where I first got the error. Might it be useful to add >0.14 to the pysam dependency in the bioconda recipe? Not sure if this is the right place for this, so sorry if it is better looked into elsewhere!

To reproduce:

```
>conda install mapdamage2 pysam=0.14
>mapDamage
```

**Comment by ginolhac** [comment]
`conda` is not really satisfying. I am planning to remove this option and let only the classic install as described under **regular installation** here. Please refer to this one.
This applies to #40 (cc @fidibidi)

**Comment by fidibidi** [comment]
Hey!

Yeah, I ended up also just following the manual install steps, and it worked great. 

Thank you!

**Comment by ginolhac** [comment]
instructions for conda are now discarded and only the regular way is written on the [website](http://ginolhac.github.io/mapDamage/) but also recalled in the README
for info:

Briefly:

- Download a [release](https://github.com/ginolhac/mapDamage/releases) as zip or tgz file
- Decompress the archive
- Install both [R](http://www.r-project.org/) and the 4 mandatory packages.
- Install the python package `pysam`
- Install mapDamage, once in the archive folder, for a user: `python setup.py install --user`
