### ISSUE TITLE
quality score of rescaled data

### ISSUE THREAD

**Issue by margeti** [ginolhac/mapDamage#43]
When using the --rescale option, in what range do the new quality scores lie in the case of a probable ancient damage?
Or, more specifically, if I call SNPs on rescaled data, which quality threshold would be safe to use, to filter out damaged bases?

**Comment by ginolhac** [comment]
damaged bases are rescaled, so why not use the same threshold as the current one you decided for?
If it is likely a damage, the score will be so low that a decent confidence will not consider this base.

**Comment by ginolhac** [comment]
closed because it has been inactive for 28 days
