### ISSUE TITLE
missing 3pGtoA_freq.txt and 5pCtoT_freq.txt tables

### ISSUE THREAD

**Issue by npsonis** [ginolhac/mapDamage#44]
Hi,

I have been using an older version. I updated recently and I noticed that the aforementioned tables are missing.
Can you confirm that this is by design and not a bug?

**Comment by MikkelSchubert** [comment]
That was intentional: 568184b15f6e878a94694361030702e6631f4050
The goal was to avoid having the same information in multiple places, but I can add it back if people are using it.

However, I haven't had time to work on mapDamage in a good while and don't know when I'll get back to it.

**Comment by ginolhac** [comment]
Thanks Mikkel. I guess we can close, if people want to have those tables, they could install the specific parent commit of yours. Or fetch the info for the current tables.
