### ISSUE TITLE
problems with mapDamage about the bam and fq files 

### ISSUE THREAD

**Issue by Alienyyy** [ginolhac/mapDamage#45]
Hi guys, I have a problem with mapDamage, I would appreciate any advice from you guys.
My sequencing data was obtained from the PE150 method. I used FastQc to check that my fq file and bam file are both less than 150bp in length, but there are very long sequences in my length_plot. And the conversion of my C to T is not obvious. Is there a mistake in the reference I chose? What are the requirements for the bam file and reference used for mapDamage? My code are shown below, and the picture of my results of mapDamage is attached.

bowtie2 -x arc -1 H1_1clean.fq.gz -2 H1_2clean.fq.gz -S H1clean.sam
samtools view -bS H1clean.sam -o H1.bam
samtools sort H1.bam -o bowtie.H1sorted.bam
picard MarkDuplicates REMOVE_DUPLICATES=true I= H1sorted.bam O=H1_sortdup.bam M=H1_dup_metrics.tx
bamtools filter -H1_sortdup.bam -out H1filter.bam -mapQuality 25
mapDamage -i H11filter.bam -r reference.fasta --merge-libraries

![1](https://user-images.githubusercontent.com/119386585/208093875-ef032171-3127-4d31-ad1d-da5c3d199701.png)
![2](https://user-images.githubusercontent.com/119386585/208093883-160f2deb-0950-4462-9531-7d6a730779e1.png)

**Comment by ginolhac** [comment]
Hello,
I do not see a problem with mapDamage. Software runs fine and delivers.
Reads are super long, maybe not ancient or contaminated with modern, hard to tell.

**Comment by Alienyyy** [comment]
Thank you so much, ginolhac. I still have some questions that really confused me: (1) What is the relationship between the bam file input by mapdamage and the reference input by mapdamage; (2) What do I need to consider when choosing a reference? (3) Is the reference modern or ancient?

**Comment by ginolhac** [comment]
Use the same reference as the one used for mapping

**Comment by Alienyyy** [comment]
Thanks a lot, ginolhac. Have a good day!
