### ISSUE TITLE
How to determine the number of bases that need to be trimmed

### ISSUE THREAD

**Issue by Pudding-Q** [ginolhac/mapDamage#46]
Dear Pro.
We used mapDamage2 to determine the DNA damage of ancient human individuals. We're not sure how to determine the number of bases that need to be trimmed for our sample with none-UDG treatment. Here is our result, is it reasonable to trim 2bp and keep pos 3 where 5pC>T is 0.00992533643313811(which is less than 0.01)?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/101164181/229745055-73ed7ad4-ab26-4f93-9fd8-f7bf1ef323e1.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/101164181/229745092-07c82121-fd42-4d94-8778-58c1031b07c8.png">

**Comment by ginolhac** [comment]
not an issue, and probably done by now
