### ISSUE TITLE
There seems to be something wrong with my Fragmisincorporation_plot

### ISSUE THREAD

**Issue by Alienyyy** [ginolhac/mapDamage#47]
Hi Ginolhac, I have some problems with my Fragmisincorporation_plot, and I really don't know why. After comparing my sequence with the reference genome, the damage should be the red end damage on the left and the blue end damage on the right. But my graph shows the opposite result, it becomes the blue end damage on the left and the red end damage on the right. Can you help me to see what is the problem? The mapped reads exceed 500. Thank you~ 
![image](https://github.com/ginolhac/mapDamage/assets/119386585/ae7af2e3-dbfb-4507-a140-c64bf711e070)

**Comment by ginolhac** [comment]
Hello,

This issue doesn't seem to be linked to mapDamage. Check if it works with test bams. Then check of your mapping flag (especially the strand flag ) are correct.

**Comment by ginolhac** [comment]
not related to mapDamage
