### ISSUE TITLE
no output figure in the result when using command "mapDamage -d /data3/dengsx_data/test/8.mapDamage/results_J5P.collapsed.sorted.filter.rmdup.final -y 0.3 --plot-only"

### ISSUE THREAD

**Issue by shaoxiong2588** [ginolhac/mapDamage#50]
the log file :
Started with the command: /public/home/dengsx/miniconda3/envs/aDNA/bin/mapDamage -d /data3/dengsx_data/test/8.mapDamage/results_J5P.collapsed.sorted.filter.rmdup.final -y 0.5 --plot-only
Error in (yaxis.at == 2) && (yaxis.at == ylabels.at) : 
  'length = 2' in coercion to 'logical(1)'
Calls: plot.base.composition -> plot.axis
3: (function (e) 
   {
       traceback(2)
       quit(status = 1)
   })()
2: plot.axis(2)
1: plot.base.composition(com, "A", "blue", OPT.AROUND, xlabels = FALSE, 
       ylabels.at = c(2, 4))
Error: plotting with R failed
additional /data3/dengsx_data/test/8.mapDamage/results_J5P.collapsed.sorted.filter.rmdup.final/Length_plot.pdf generated

How to fix it

**Comment by ginolhac** [comment]
Use R version < 4.3.0

**Comment by ginolhac** [comment]
or update to [**version 2.2.2**](https://github.com/ginolhac/mapDamage/releases/tag/2.2.2)
