### ISSUE TITLE
The ACGT frequencies do not sum to 1 error

### ISSUE THREAD

**Issue by ksavhughes** [ginolhac/mapDamage#51]
![Screen Shot 2023-08-23 at 1 28 04 PM](https://github.com/ginolhac/mapDamage/assets/82043991/10e283c5-a982-4f1a-9e62-a9bf61fd0973)

I keep getting this error for any sample that I map to NC_008092.1, the refseq gray wolf reference mitochondrial genome. I'll run the same samples using a different reference and don't get any errors. Can you help me figure this error out and why it is only coming up for this reference?

Karissa

**Comment by ginolhac** [comment]
Could you please upload the simulation folder, probably the zip of  `results` 
thanks

**Comment by ksavhughes** [comment]
[MapDamage_results.tar.gz](https://github.com/ginolhac/mapDamage/files/12431436/MapDamage_results.tar.gz)

Here is the results folder. We use the rescaled bam file for downstream analyses and we're confused why is errors out during that step.

**Comment by ginolhac** [comment]
thanks, at least it is not the `dnacomp_genome.csv` , this one does sum up to one
``` r
 0.3161136023916293+0.25542600896860984+0.1414050822122571+0.2870553064275037
[1] 1
```

**Comment by MikkelSchubert** [comment]
I've pushed a fix for this bug (plus some other changes). Please give it a try and let us know fixes the problem for you

Cheers,
Mikkel
