### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by PKazakova** [ginolhac/mapDamage#52]
Hello! Thank you for tool!
I used mapDamage v2.2.2 and had an error:
```
Traceback (most recent call last):
  File "/soft/mapDamage/mapDamage", line 33, in <module>
    sys.exit(load_entry_point('mapdamage==2.2.1', 'console_scripts', 'mapDamage')())
  File "/soft/mapDamage/mapdamage/main.py", line 270, in entry_point
    return main(sys.argv[1:])
  File "/soft/mapDamage/mapdamage/main.py", line 249, in main
    options.ref, options.folder / "dnacomp_genome.csv"
  File "/soft/mapDamage/mapdamage/composition.py", line 11, in write_base_comp
    for stats in seqtk.comp(str(fasta)):
AttributeError: module 'mapdamage.seqtk' has no attribute 'comp'
```
Could you fix it?

Best regards, Polina.

**Comment by MikkelSchubert** [comment]
The error message you got is unique to the development version of mapDamage, so if you intended to run 2.2.2 then you must have multiple (conflicting) versions of mapDamage installed. If so then I'd suggest uninstalling all copies of mapDamage and reinstalling the version you actually wanted to run.

If you did want to use the development version of mapDamage, then you will need to reinstall it as the `seqtk` module wasn't built during installation. Did you get any error messages when you installed it? The module *should* have been built automatically.

Cheers,
Mikkel

**Comment by ginolhac** [comment]
I guess Mikkel suggestion worked out
