### ISSUE TITLE
Questions about Position-Frequency plot 

### ISSUE THREAD

**Issue by timeresistance1996** [ginolhac/mapDamage#54]
Hallo, 
  
 I am a beginner in the field of genetic damage, and I have some questions about analyzing the mapDamage results.

For the Position-Frequency plot, first, does "frequency" correspond to the number of a specific base mutation (such as C>T) divided by the total number of C bases in the sequence? Secondly, does 1-25 mean the sequence position of the N-th C base from 5' to 3'?

**Comment by ginolhac** [comment]
Hallo,
yes and yes, correct

**Comment by timeresistance1996** [comment]
Ha-ha, thank you so much!
